### ISSUE TITLE
Changing issue

### ISSUE THREAD

**Issue by h4zzkR** [samuelcarreira/dynamic-time-shifting-desktop#1]
Ubuntu 18.04. App started, but wallpapers didn't change. Log:
`{"message":"========= Welcome to Dynamic Time-shifting Desktop v.1.0.2 =========","level":"info","timestamp":"2018-07-14T15:11:14.353Z"}
{"message":"Wallpaper changed to: /opt/Dynamic Time-shifting Desktop/resources/sample-wallpapers/12.jpeg","level":"info","timestamp":"2018-07-14T15:11:14.531Z"}
{"message":"Application exiting...","level":"info","timestamp":"2018-07-14T15:11:22.128Z"}
{"message":"========= Welcome to Dynamic Time-shifting Desktop v.1.0.2 =========","level":"info","timestamp":"2018-07-14T15:19:54.477Z"}
{"message":"Wallpaper changed to: /opt/Dynamic Time-shifting Desktop/resources/sample-wallpapers/12.jpeg","level":"info","timestamp":"2018-07-14T15:19:54.595Z"}
{"message":"Checking for updates...","level":"info","timestamp":"2018-07-14T15:20:24.594Z"}
{"message":"Update not available","level":"info","timestamp":"2018-07-14T15:20:25.170Z"}
{"message":"Application exiting...","level":"info","timestamp":"2018-07-14T15:21:01.955Z"}`
Seems like it changes wallpaper, but system does not allow it.

**Comment by h4zzkR** [comment]
Oh, sorry. On vanilla GNOME works good.

**Comment by h4zzkR** [comment]
I'm sorry again, now app can't stay active. When I press "minimise" it just exits, as I can see in log:
`{"message":"Uncaught Exception: Error: Cannot find module './AutoLaunchLinux'","level":"error","timestamp":"2018-07-15T17:21:17.940Z"}`

**Comment by h4zzkR** [comment]
Sorry, sorry, my sorry again. It solved with disabling "Minimise to tray" function.

**Comment by samuelcarreira** [comment]
Ok no problem, check if app icon appears near clock. On some Linux desktop environments you can have some problems.

Also, can you specify your Linux distribution details (or iso link) and if you change any default setting concerning the default desktop environment?
(I’ve to add some extra code to wallpaper module to resolve some compatibility issues with the lubuntu and the Ubuntu distros)

**Comment by h4zzkR** [comment]
No icon near the clock.
Ubuntu 18.04 LTS x86_64 
Vanilla Gnome Shell 3.28.2
I just changed my theme to MacOs Mojave dark and system font. Installed some extensions as Dash to dock, Caffeine, media player icon, no topleft corner, hide top bar and dynamic topbar. But they don't contact with wallpaper.

**Comment by h4zzkR** [comment]
No icon, but suddenly solved the problem with re-enabling app's autolaunch. Thanks again for this useful app!
